# Generated by Django 4.1.5 on 2023-04-03 13:44

import ShoppingLists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0002_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to=ShoppingLists.models.upload_to),
        ),
    ]
