# Generated by Django 4.1.5 on 2023-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0002_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=1000),
        ),
    ]
