# Generated by Django 4.1.5 on 2023-03-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='shoppinglist_product',
            new_name='product',
        ),
    ]
