# Generated by Django 4.0.2 on 2023-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0003_alter_product_image_url_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
