# Generated by Django 4.1.5 on 2023-04-04 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShoppingLists', '0003_alter_product_image_url_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_product', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
