# Generated by Django 4.1.5 on 2023-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user_alter_product_collection'),
        ('ShoppingLists', '0004_remove_collection_user_remove_shoppinglist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_item', to='products.product'),
        ),
    ]
