# Generated by Django 4.1.5 on 2023-03-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user_alter_product_collection'),
        ('ShoppingLists', '0005_alter_collection_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='products.product'),
        ),
    ]
