# Generated by Django 4.1.5 on 2023-04-04 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShoppingLists', '0005_remove_product_favorite_product_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
