# Generated by Django 4.1.5 on 2023-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0008_product_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
    ]
