# Generated by Django 4.1.5 on 2023-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
