# Generated by Django 4.1.5 on 2023-03-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingLists', '0004_remove_collection_user_remove_shoppinglist_user_and_more'),
        ('products', '0002_alter_product_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_item', to='ShoppingLists.collection'),
        ),
    ]
