# Generated by Django 4.1.5 on 2023-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
