# Generated by Django 4.1.5 on 2023-04-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite',
        ),
    ]
