# Generated by Django 4.1.5 on 2023-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_favorites',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
